### ISSUE TITLE
Content Creator: Pricing add-on Plugin

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#310]
Pricing add-on plugin

```gherkin
Feature: Pricing add-on
  As a Content Creator,
  I want an input plugin for Pricing add-on for the API content type
  So that user can add additional pricing information

  Scenario: Name
    Given Pricing add-on would require a name
     When I enter content about Pricing add-on
     Then I would need to enter the name
      And data type would be text
      And this type is required to save

  Scenario: Description
    Given Pricing add-on would require a description
     When I enter content about Pricing add-on
     Then I would need to enter the description
      And data type would be long text

  Scenario: Cost
    Given Pricing add-on might require paid cost (in US Dollars)
     When I enter content about Pricing add-on
     Then I would need to enter paid cost
      And data type would be a number
      And limit would currency and $xxx.xx

  Scenario: Unit of measure
    Given Pricing add-on might require unit in which it is measured
     When I enter content about Pricing add-on
     Then I would need to enter unit
      And data type would be a text
```

---

**Pricing add-on**
- [ ] Name
- [ ] Description
- [ ] Cost
- [ ] Unit of measure

**Comment by ineedsubstance** [comment]
Blocked by https://github.com/punchcard-cms/punchcard/issues/179

**Comment by ineedsubstance** [comment]
Blocker for https://github.ibm.com/Watson/wox-cms/issues/404

**Comment by ineedsubstance** [comment]
You can find the code [here](https://github.ibm.com/Watson/wox-cms/blob/develop/content-models/api.yml#L198)

```yaml
  - title: Pricing Add-ons
    description: Pricing add-ons
    repeatable: true
    type: object
      - title: Name
        description: Name of Pricing add-on
        type: text
      - title: Description
        description: Pricing add-on description
        type: long text
      - title: Cost
        type: number
        description: Add-on cost (in US Dollars)
        limit: currency, $xxx.xx
      - title: Unit of measure
        type: text
        description: Unit that pricing is measured in
```
